module.exports = [
  // OAHU NORTH SHORE — Pipeline confirmed 10ft/16s
  {id:"pipeline",      name:"Pipeline / Backdoor",        region:"Oahu North Shore",location:"Ehukai Beach, HI",     buoyId:"51201",lat:21.665,lon:-158.053,offshoreWindFrom:112,tideStation:"1612480",tideMin:0.0,tideMax:1.5,tideMovement:"any",   minHeight:10,minPeriod:16,maxWindKts:20,idealSwell:["NW","WNW","NNW","N"]},
  {id:"sunset",        name:"Sunset Beach",               region:"Oahu North Shore",location:"Sunset Beach, HI",     buoyId:"51201",lat:21.678,lon:-158.040,offshoreWindFrom:157,tideStation:"1612480",tideMin:0.0,tideMax:1.8,tideMovement:"any",   minHeight:8, minPeriod:14,maxWindKts:20,idealSwell:["NW","NNW","N","WNW"]},
  {id:"waimea",        name:"Waimea Bay",                 region:"Oahu North Shore",location:"Haleiwa, HI",          buoyId:"51201",lat:21.642,lon:-158.066,offshoreWindFrom:112,tideStation:"1612480",tideMin:0.0,tideMax:2.0,tideMovement:"any",   minHeight:15,minPeriod:16,maxWindKts:20,idealSwell:["NW","NNW","N","WNW"],bigWaveSpot:true},
  {id:"haleiwa",       name:"Haleiwa Ali'i Beach",        region:"Oahu North Shore",location:"Haleiwa, HI",          buoyId:"51201",lat:21.595,lon:-158.110,offshoreWindFrom:135,tideStation:"1612480",tideMin:0.0,tideMax:1.8,tideMovement:"any",   minHeight:5, minPeriod:13,maxWindKts:16,idealSwell:["NW","NNW","N","WNW"]},
  {id:"laniakea",      name:"Laniakea",                   region:"Oahu North Shore",location:"Haleiwa, HI",          buoyId:"51201",lat:21.627,lon:-158.086,offshoreWindFrom:135,tideStation:"1612480",tideMin:0.0,tideMax:1.8,tideMovement:"any",   minHeight:5, minPeriod:13,maxWindKts:16,idealSwell:["NW","NNW","N","WNW"]},
  {id:"chuns_reef",    name:"Chun's Reef",                region:"Oahu North Shore",location:"Haleiwa, HI",          buoyId:"51201",lat:21.638,lon:-158.074,offshoreWindFrom:135,tideStation:"1612480",tideMin:0.0,tideMax:1.8,tideMovement:"any",   minHeight:4, minPeriod:12,maxWindKts:16,idealSwell:["NW","NNW","N","WNW"]},
  {id:"rockpiles",     name:"Rock Piles",                 region:"Oahu North Shore",location:"Haleiwa, HI",          buoyId:"51201",lat:21.635,lon:-158.073,offshoreWindFrom:135,tideStation:"1612480",tideMin:0.0,tideMax:1.8,tideMovement:"any",   minHeight:6, minPeriod:14,maxWindKts:16,idealSwell:["NW","NNW","N","WNW"]},
  {id:"puaena",        name:"Pua'ena Point",              region:"Oahu North Shore",location:"Haleiwa, HI",          buoyId:"51201",lat:21.598,lon:-158.104,offshoreWindFrom:135,tideStation:"1612480",tideMin:0.0,tideMax:1.8,tideMovement:"any",   minHeight:4, minPeriod:12,maxWindKts:16,idealSwell:["NW","NNW","N","WNW"]},
  {id:"velzyland",     name:"Velzyland (V-Land)",         region:"Oahu North Shore",location:"Kahuku, HI",           buoyId:"51201",lat:21.688,lon:-157.984,offshoreWindFrom:135,tideStation:"1612480",tideMin:0.0,tideMax:1.8,tideMovement:"any",   minHeight:6, minPeriod:14,maxWindKts:16,idealSwell:["N","NNE","NE"]},
  {id:"phantoms",      name:"Phantoms",                   region:"Oahu North Shore",location:"Haleiwa, HI",          buoyId:"51201",lat:21.644,lon:-158.068,offshoreWindFrom:135,tideStation:"1612480",tideMin:0.0,tideMax:1.8,tideMovement:"any",   minHeight:8, minPeriod:15,maxWindKts:16,idealSwell:["NW","NNW","N","WNW"]},
  {id:"leftovers",     name:"Leftovers",                  region:"Oahu North Shore",location:"Haleiwa, HI",          buoyId:"51201",lat:21.630,lon:-158.079,offshoreWindFrom:135,tideStation:"1612480",tideMin:0.0,tideMax:1.8,tideMovement:"any",   minHeight:5, minPeriod:13,maxWindKts:16,idealSwell:["NW","NNW","N","WNW"]},
  {id:"log_cabins",    name:"Log Cabins",                 region:"Oahu North Shore",location:"Pupukea, HI",          buoyId:"51201",lat:21.664,lon:-158.056,offshoreWindFrom:135,tideStation:"1612480",tideMin:0.0,tideMax:1.5,tideMovement:"any",   minHeight:6, minPeriod:14,maxWindKts:16,idealSwell:["N","NNW","NW","NNE"]},
  {id:"off_the_wall",  name:"Off the Wall / Kodak Reef",  region:"Oahu North Shore",location:"Ehukai, HI",           buoyId:"51201",lat:21.666,lon:-158.052,offshoreWindFrom:135,tideStation:"1612480",tideMin:0.0,tideMax:1.5,tideMovement:"any",   minHeight:5, minPeriod:13,maxWindKts:16,idealSwell:["N","NNW","NW"]},
  {id:"alligators",    name:"Alligator Rock",             region:"Oahu North Shore",location:"Pupukea, HI",          buoyId:"51201",lat:21.660,lon:-158.061,offshoreWindFrom:135,tideStation:"1612480",tideMin:0.0,tideMax:1.5,tideMovement:"any",   minHeight:5, minPeriod:13,maxWindKts:16,idealSwell:["N","NNW","NW"]},
  // OAHU SOUTH SHORE
  {id:"ala_moana",     name:"Ala Moana Bowls",            region:"Oahu South Shore",location:"Honolulu, HI",         buoyId:"openmeteo",dataSource:"openmeteo",lat:21.284,lon:-157.858,offshoreWindFrom:0,  tideStation:"1612340",tideMin:0.0,tideMax:2.0,tideMovement:"any",   minHeight:4, minPeriod:13,maxWindKts:16,idealSwell:["S","SSW","SW","SSE"]},
  {id:"queens",        name:"Queen's / Canoes",           region:"Oahu South Shore",location:"Waikiki, HI",          buoyId:"openmeteo",dataSource:"openmeteo",lat:21.276,lon:-157.829,offshoreWindFrom:0,  tideStation:"1612340",tideMin:0.0,tideMax:2.0,tideMovement:"any",   minHeight:4, minPeriod:12,maxWindKts:16,idealSwell:["S","SSW","SW","SE"]},
  {id:"kaisers",       name:"Kaiser's",                   region:"Oahu South Shore",location:"Waikiki, HI",          buoyId:"openmeteo",dataSource:"openmeteo",lat:21.272,lon:-157.835,offshoreWindFrom:0,  tideStation:"1612340",tideMin:0.0,tideMax:2.0,tideMovement:"any",   minHeight:4, minPeriod:13,maxWindKts:16,idealSwell:["S","SSW","SW"]},
  {id:"diamond_head",  name:"Diamond Head Lighthouse",    region:"Oahu South Shore",location:"Diamond Head, HI",     buoyId:"openmeteo",dataSource:"openmeteo",lat:21.257,lon:-157.804,offshoreWindFrom:0,  tideStation:"1612340",tideMin:0.0,tideMax:2.0,tideMovement:"any",   minHeight:4, minPeriod:13,maxWindKts:16,idealSwell:["S","SSW","SE","SSE"]},
  {id:"populars",      name:"Populars",                   region:"Oahu South Shore",location:"Waikiki, HI",          buoyId:"openmeteo",dataSource:"openmeteo",lat:21.274,lon:-157.824,offshoreWindFrom:0,  tideStation:"1612340",tideMin:0.0,tideMax:2.0,tideMovement:"any",   minHeight:4, minPeriod:12,maxWindKts:16,idealSwell:["S","SW","SSW"]},
  {id:"baby_haleiwa",  name:"Point Panic",                region:"Oahu South Shore",location:"Honolulu, HI",         buoyId:"openmeteo",dataSource:"openmeteo",lat:21.294,lon:-157.870,offshoreWindFrom:0,  tideStation:"1612340",tideMin:0.0,tideMax:2.0,tideMovement:"any",   minHeight:4, minPeriod:13,maxWindKts:16,idealSwell:["S","SSW","SW"]},
  {id:"four_to_one",   name:"4 to 1",                    region:"Oahu South Shore",location:"Honolulu, HI",         buoyId:"openmeteo",dataSource:"openmeteo",lat:21.276,lon:-157.841,offshoreWindFrom:0,  tideStation:"1612340",tideMin:0.0,tideMax:2.0,tideMovement:"any",   minHeight:4, minPeriod:12,maxWindKts:16,idealSwell:["S","SSW","SW"]},
  // OAHU EAST
  {id:"sandy_beach",   name:"Sandy Beach",                region:"Oahu East",       location:"Sandy Beach, HI",      buoyId:"openmeteo",dataSource:"openmeteo",lat:21.296,lon:-157.673,offshoreWindFrom:270,tideStation:"1612340",tideMin:0.0,tideMax:1.5,tideMovement:"any",   minHeight:4, minPeriod:11,maxWindKts:16,idealSwell:["E","ENE","NE","SE"]},
  {id:"makapuu",       name:"Makapu'u",                   region:"Oahu East",       location:"Waimanalo, HI",        buoyId:"openmeteo",dataSource:"openmeteo",lat:21.310,lon:-157.652,offshoreWindFrom:270,tideStation:"1612340",tideMin:0.0,tideMax:1.5,tideMovement:"any",   minHeight:4, minPeriod:12,maxWindKts:16,idealSwell:["E","ENE","NE"]},
  {id:"china_walls",   name:"China Walls",                region:"Oahu East",       location:"Portlock, HI",         buoyId:"openmeteo",dataSource:"openmeteo",lat:21.274,lon:-157.719,offshoreWindFrom:315,tideStation:"1612340",tideMin:0.0,tideMax:1.5,tideMovement:"any",   minHeight:4, minPeriod:12,maxWindKts:16,idealSwell:["S","SE","SSE"]},
  {id:"suicides",      name:"Suicides (Portlock)",        region:"Oahu East",       location:"Hawaii Kai, HI",       buoyId:"openmeteo",dataSource:"openmeteo",lat:21.276,lon:-157.714,offshoreWindFrom:315,tideStation:"1612340",tideMin:0.0,tideMax:1.5,tideMovement:"any",   minHeight:5, minPeriod:13,maxWindKts:16,idealSwell:["S","SE","SSE"]},
  {id:"wawamalu",      name:"Wawamalu (Billy Goats)",     region:"Oahu East",       location:"Sandy Beach, HI",      buoyId:"openmeteo",dataSource:"openmeteo",lat:21.301,lon:-157.664,offshoreWindFrom:270,tideStation:"1612340",tideMin:0.0,tideMax:1.5,tideMovement:"any",   minHeight:4, minPeriod:11,maxWindKts:16,idealSwell:["E","ENE","SE"]},
  // OAHU WEST
  {id:"makaha",        name:"Makaha Beach",               region:"Oahu West",       location:"Makaha, HI",           buoyId:"51201",lat:21.474,lon:-158.217,offshoreWindFrom:90, tideStation:"1612340",tideMin:0.0,tideMax:1.8,tideMovement:"any",   minHeight:5, minPeriod:13,maxWindKts:16,idealSwell:["NW","WNW","W"]},
  {id:"yokohama",      name:"Yokohama Bay",               region:"Oahu West",       location:"Waianae, HI",          buoyId:"51201",lat:21.549,lon:-158.280,offshoreWindFrom:90, tideStation:"1612340",tideMin:0.0,tideMax:1.8,tideMovement:"any",   minHeight:4, minPeriod:12,maxWindKts:16,idealSwell:["NW","W","WNW"]},
  {id:"pray_for_sex",  name:"Pray for Sex",               region:"Oahu West",       location:"Waianae, HI",          buoyId:"51201",lat:21.479,lon:-158.209,offshoreWindFrom:90, tideStation:"1612340",tideMin:0.0,tideMax:1.8,tideMovement:"any",   minHeight:4, minPeriod:12,maxWindKts:16,idealSwell:["NW","W","WNW"]},
  // MAUI
  {id:"jaws",          name:"Pe'ahi (Jaws)",              region:"Maui",            location:"Haiku, HI",            buoyId:"openmeteo",dataSource:"openmeteo",lat:20.943,lon:-156.310,offshoreWindFrom:202,tideStation:"1615680",tideMin:0.0,tideMax:2.0,tideMovement:"any",   minHeight:20,minPeriod:17,maxWindKts:20,idealSwell:["NW","NNW","N","WNW"],bigWaveSpot:true},
  {id:"hookipa",       name:"Ho'okipa Beach",             region:"Maui",            location:"Paia, HI",             buoyId:"openmeteo",dataSource:"openmeteo",lat:20.936,lon:-156.340,offshoreWindFrom:225,tideStation:"1615680",tideMin:0.0,tideMax:2.0,tideMovement:"any",   minHeight:5, minPeriod:13,maxWindKts:16,idealSwell:["N","NE","NNE","ENE"]},
  {id:"honolua_bay",   name:"Honolua Bay",                region:"Maui",            location:"Kapalua, HI",          buoyId:"openmeteo",dataSource:"openmeteo",lat:21.015,lon:-156.643,offshoreWindFrom:135,tideStation:"1615680",tideMin:0.0,tideMax:2.0,tideMovement:"any",   minHeight:6, minPeriod:14,maxWindKts:16,idealSwell:["NNW","NW","N","WNW"]},
  {id:"lahaina_bw",    name:"Lahaina Breakwall",          region:"Maui",            location:"Lahaina, HI",          buoyId:"openmeteo",dataSource:"openmeteo",lat:20.874,lon:-156.682,offshoreWindFrom:90, tideStation:"1615680",tideMin:0.0,tideMax:2.0,tideMovement:"any",   minHeight:4, minPeriod:12,maxWindKts:16,idealSwell:["SW","S","SSW","W"]},
  {id:"launiupoko",    name:"Launiupoko",                 region:"Maui",            location:"Lahaina, HI",          buoyId:"openmeteo",dataSource:"openmeteo",lat:20.865,lon:-156.664,offshoreWindFrom:90, tideStation:"1615680",tideMin:0.0,tideMax:2.0,tideMovement:"any",   minHeight:3, minPeriod:11,maxWindKts:12,idealSwell:["SW","S","W"]},
  {id:"thousand_peaks",name:"Thousand Peaks",             region:"Maui",            location:"Olowalu, HI",          buoyId:"openmeteo",dataSource:"openmeteo",lat:20.816,lon:-156.601,offshoreWindFrom:90, tideStation:"1615680",tideMin:0.0,tideMax:2.0,tideMovement:"rising",minHeight:3, minPeriod:11,maxWindKts:12,idealSwell:["SW","S","W"]},
  {id:"maalaea",       name:"Ma'alaea (Freight Trains)",  region:"Maui",            location:"Maalaea, HI",          buoyId:"openmeteo",dataSource:"openmeteo",lat:20.790,lon:-156.507,offshoreWindFrom:45, tideStation:"1615680",tideMin:0.0,tideMax:1.5,tideMovement:"any",   minHeight:4, minPeriod:13,maxWindKts:16,idealSwell:["S","SSW","SW"]},
  {id:"dumps",         name:"Dumps (Lauapo'o)",           region:"Maui",            location:"Kihei, HI",            buoyId:"openmeteo",dataSource:"openmeteo",lat:20.762,lon:-156.456,offshoreWindFrom:315,tideStation:"1615680",tideMin:0.0,tideMax:1.8,tideMovement:"any",   minHeight:4, minPeriod:12,maxWindKts:16,idealSwell:["S","SSW","SW"]},
  {id:"kalama",        name:"Kalama Beach Park",          region:"Maui",            location:"Kihei, HI",            buoyId:"openmeteo",dataSource:"openmeteo",lat:20.754,lon:-156.448,offshoreWindFrom:315,tideStation:"1615680",tideMin:0.0,tideMax:2.0,tideMovement:"rising",minHeight:3, minPeriod:11,maxWindKts:16,idealSwell:["S","SW","SSW"]},
  // KAUAI
  {id:"hanalei",       name:"Hanalei Bay",                region:"Kauai",           location:"Hanalei, HI",          buoyId:"openmeteo",dataSource:"openmeteo",lat:22.205,lon:-159.500,offshoreWindFrom:180,tideStation:"1611400",tideMin:0.0,tideMax:2.0,tideMovement:"any",   minHeight:5, minPeriod:14,maxWindKts:16,idealSwell:["N","NW","NNW","NNE"]},
  {id:"tunnels",       name:"Tunnels (Makua)",            region:"Kauai",           location:"Haena, HI",            buoyId:"openmeteo",dataSource:"openmeteo",lat:22.217,lon:-159.567,offshoreWindFrom:180,tideStation:"1611400",tideMin:0.0,tideMax:2.0,tideMovement:"any",   minHeight:5, minPeriod:14,maxWindKts:16,idealSwell:["N","NW","NNW"]},
  {id:"hanalei_pier",  name:"Hanalei Pier",               region:"Kauai",           location:"Hanalei, HI",          buoyId:"openmeteo",dataSource:"openmeteo",lat:22.204,lon:-159.499,offshoreWindFrom:180,tideStation:"1611400",tideMin:0.0,tideMax:2.0,tideMovement:"rising",minHeight:4, minPeriod:12,maxWindKts:16,idealSwell:["N","NNW","NW","NE"]},
  {id:"polihale",      name:"Polihale State Park",        region:"Kauai",           location:"Kekaha, HI",           buoyId:"openmeteo",dataSource:"openmeteo",lat:22.080,lon:-159.782,offshoreWindFrom:90, tideStation:"1611400",tideMin:0.0,tideMax:2.0,tideMovement:"any",   minHeight:5, minPeriod:13,maxWindKts:16,idealSwell:["NW","WNW","W"]},
  {id:"pakala",        name:"Pakala (Infinities)",        region:"Kauai",           location:"Waimea, HI",           buoyId:"openmeteo",dataSource:"openmeteo",lat:21.958,lon:-159.692,offshoreWindFrom:90, tideStation:"1611400",tideMin:0.0,tideMax:2.0,tideMovement:"any",   minHeight:4, minPeriod:13,maxWindKts:16,idealSwell:["SW","S","SSW","W"]},
  {id:"shipwreck",     name:"Shipwreck Beach",            region:"Kauai",           location:"Poipu, HI",            buoyId:"openmeteo",dataSource:"openmeteo",lat:21.872,lon:-159.444,offshoreWindFrom:0,  tideStation:"1611400",tideMin:0.0,tideMax:2.0,tideMovement:"any",   minHeight:4, minPeriod:12,maxWindKts:16,idealSwell:["S","SSW","SW","SE"]},
  {id:"poipu",         name:"Poipu Beach",                region:"Kauai",           location:"Poipu, HI",            buoyId:"openmeteo",dataSource:"openmeteo",lat:21.874,lon:-159.438,offshoreWindFrom:0,  tideStation:"1611400",tideMin:0.0,tideMax:2.0,tideMovement:"rising",minHeight:3, minPeriod:11,maxWindKts:16,idealSwell:["S","SW","SSW"]},
  {id:"kealia",        name:"Kealia Beach",               region:"Kauai",           location:"Kapaa, HI",            buoyId:"openmeteo",dataSource:"openmeteo",lat:22.068,lon:-159.328,offshoreWindFrom:270,tideStation:"1611400",tideMin:0.0,tideMax:2.0,tideMovement:"rising",minHeight:4, minPeriod:12,maxWindKts:16,idealSwell:["E","NE","ENE"]},
  {id:"anahola",       name:"Anahola Beach",              region:"Kauai",           location:"Anahola, HI",          buoyId:"openmeteo",dataSource:"openmeteo",lat:22.146,lon:-159.310,offshoreWindFrom:270,tideStation:"1611400",tideMin:0.0,tideMax:2.0,tideMovement:"rising",minHeight:4, minPeriod:12,maxWindKts:16,idealSwell:["NE","E","ENE"]},
  {id:"majors_bay",    name:"Major's Bay",                region:"Kauai",           location:"Hanapepe, HI",         buoyId:"openmeteo",dataSource:"openmeteo",lat:21.910,lon:-159.583,offshoreWindFrom:0,  tideStation:"1611400",tideMin:0.0,tideMax:2.0,tideMovement:"any",   minHeight:4, minPeriod:12,maxWindKts:16,idealSwell:["SW","S","W"]},
  // BIG ISLAND
  {id:"banyans",       name:"Banyan's",                   region:"Big Island",      location:"Kailua-Kona, HI",      buoyId:"openmeteo",dataSource:"openmeteo",lat:19.639,lon:-155.996,offshoreWindFrom:90, tideStation:"1617760",tideMin:0.0,tideMax:2.0,tideMovement:"any",   minHeight:4, minPeriod:11,maxWindKts:16,idealSwell:["NW","W","SW"]},
  {id:"pinetrees",     name:"Pine Trees",                 region:"Big Island",      location:"Kona, HI",             buoyId:"openmeteo",dataSource:"openmeteo",lat:19.684,lon:-156.020,offshoreWindFrom:90, tideStation:"1617760",tideMin:0.0,tideMax:2.0,tideMovement:"rising",minHeight:3, minPeriod:11,maxWindKts:16,idealSwell:["NW","W","SW"]},
  {id:"honolii",       name:"Honoli'i Beach",             region:"Big Island",      location:"Hilo, HI",             buoyId:"openmeteo",dataSource:"openmeteo",lat:19.753,lon:-155.060,offshoreWindFrom:270,tideStation:"1617433",tideMin:0.0,tideMax:2.0,tideMovement:"rising",minHeight:4, minPeriod:11,maxWindKts:16,idealSwell:["NE","E","ENE"]},
  {id:"richardsons",   name:"Richardson's Ocean Park",    region:"Big Island",      location:"Hilo, HI",             buoyId:"openmeteo",dataSource:"openmeteo",lat:19.723,lon:-155.029,offshoreWindFrom:270,tideStation:"1617433",tideMin:0.0,tideMax:2.0,tideMovement:"rising",minHeight:4, minPeriod:11,maxWindKts:16,idealSwell:["E","NE","ENE"]},
  {id:"kahaluu",       name:"Kahalu'u Beach Park",        region:"Big Island",      location:"Keauhou, HI",          buoyId:"openmeteo",dataSource:"openmeteo",lat:19.578,lon:-156.011,offshoreWindFrom:90, tideStation:"1617760",tideMin:0.0,tideMax:2.0,tideMovement:"rising",minHeight:3, minPeriod:11,maxWindKts:16,idealSwell:["NW","W","SW"]},
  {id:"lymans",        name:"Lyman's",                    region:"Big Island",      location:"Kailua-Kona, HI",      buoyId:"openmeteo",dataSource:"openmeteo",lat:19.628,lon:-155.997,offshoreWindFrom:90, tideStation:"1617760",tideMin:0.0,tideMax:2.0,tideMovement:"any",   minHeight:4, minPeriod:12,maxWindKts:16,idealSwell:["NW","W","SW"]},
  // MOLOKAI
  {id:"dixie_maru",    name:"Dixie Maru (Kapukahehu)",    region:"Molokai",         location:"Maunaloa, HI",         buoyId:"openmeteo",dataSource:"openmeteo",lat:21.116,lon:-157.262,offshoreWindFrom:90, tideStation:"1612340",tideMin:0.0,tideMax:2.0,tideMovement:"any",   minHeight:4, minPeriod:12,maxWindKts:16,idealSwell:["NW","W","WNW","SW"]},
  {id:"halawa",        name:"Halawa Bay",                 region:"Molokai",         location:"Halawa, HI",           buoyId:"openmeteo",dataSource:"openmeteo",lat:21.168,lon:-156.739,offshoreWindFrom:270,tideStation:"1612340",tideMin:0.0,tideMax:2.0,tideMovement:"rising",minHeight:3, minPeriod:11,maxWindKts:16,idealSwell:["NE","N","NNE"]},
  // LANAI
  {id:"shipwreck_lanai",name:"Shipwreck Beach (Lanai)",   region:"Lanai",           location:"Lanai City, HI",       buoyId:"openmeteo",dataSource:"openmeteo",lat:20.923,lon:-156.842,offshoreWindFrom:270,tideStation:"1612340",tideMin:0.0,tideMax:2.0,tideMovement:"rising",minHeight:4, minPeriod:12,maxWindKts:16,idealSwell:["NE","N","NNE"]},

  // ── OAHU SOUTH SHORE ADDITIONS ──────────────────────
  {id:"publics",          name:"Public's (Ala Moana)",       region:"Oahu South Shore", location:"Honolulu, HI",        buoyId:"openmeteo",dataSource:"openmeteo",lat:21.290,lon:-157.863,offshoreWindFrom:0,  tideStation:"1612340",tideMin:0.0,tideMax:2.0,tideMovement:"any",   minHeight:4,minPeriod:12,maxWindKts:16,idealSwell:["S","SSW","SW"]},
  {id:"rice_bowls",       name:"Rice Bowls",                 region:"Oahu South Shore", location:"Honolulu, HI",        buoyId:"openmeteo",dataSource:"openmeteo",lat:21.285,lon:-157.853,offshoreWindFrom:0,  tideStation:"1612340",tideMin:0.0,tideMax:2.0,tideMovement:"any",   minHeight:4,minPeriod:13,maxWindKts:16,idealSwell:["S","SSW","SW"]},
  {id:"fours",            name:"Fours",                      region:"Oahu South Shore", location:"Waikiki, HI",         buoyId:"openmeteo",dataSource:"openmeteo",lat:21.275,lon:-157.833,offshoreWindFrom:0,  tideStation:"1612340",tideMin:0.0,tideMax:2.0,tideMovement:"any",   minHeight:4,minPeriod:12,maxWindKts:16,idealSwell:["S","SW","SSW"]},
  {id:"threes",           name:"Threes",                     region:"Oahu South Shore", location:"Waikiki, HI",         buoyId:"openmeteo",dataSource:"openmeteo",lat:21.274,lon:-157.826,offshoreWindFrom:0,  tideStation:"1612340",tideMin:0.0,tideMax:2.0,tideMovement:"any",   minHeight:4,minPeriod:12,maxWindKts:16,idealSwell:["S","SW","SSW"]},
  {id:"in_betweens",      name:"In Betweens",                region:"Oahu South Shore", location:"Waikiki, HI",         buoyId:"openmeteo",dataSource:"openmeteo",lat:21.273,lon:-157.828,offshoreWindFrom:0,  tideStation:"1612340",tideMin:0.0,tideMax:2.0,tideMovement:"any",   minHeight:4,minPeriod:12,maxWindKts:16,idealSwell:["S","SSW","SW"]},
  {id:"graveyards",       name:"Graveyards",                 region:"Oahu South Shore", location:"Waikiki, HI",         buoyId:"openmeteo",dataSource:"openmeteo",lat:21.270,lon:-157.820,offshoreWindFrom:0,  tideStation:"1612340",tideMin:0.0,tideMax:2.0,tideMovement:"any",   minHeight:4,minPeriod:13,maxWindKts:16,idealSwell:["S","SSW","SE"]},
  {id:"kewalo_basin",     name:"Kewalo Basin",               region:"Oahu South Shore", location:"Honolulu, HI",        buoyId:"openmeteo",dataSource:"openmeteo",lat:21.295,lon:-157.868,offshoreWindFrom:0,  tideStation:"1612340",tideMin:0.0,tideMax:2.0,tideMovement:"any",   minHeight:4,minPeriod:12,maxWindKts:16,idealSwell:["S","SSW","SW"]},

  // ── OAHU NORTH SHORE ADDITIONS ──────────────────────
  {id:"himalayas",        name:"Himalayas",                  region:"Oahu North Shore", location:"Haleiwa, HI",         buoyId:"51201",lat:21.650,lon:-158.062,offshoreWindFrom:135,tideStation:"1612480",tideMin:0.0,tideMax:1.5,tideMovement:"any",   minHeight:8,minPeriod:14,maxWindKts:16,idealSwell:["NW","NNW","N","WNW"]},
  {id:"freddyland",       name:"Freddy Land",                region:"Oahu North Shore", location:"Haleiwa, HI",         buoyId:"51201",lat:21.636,lon:-158.072,offshoreWindFrom:135,tideStation:"1612480",tideMin:0.0,tideMax:1.5,tideMovement:"any",   minHeight:5,minPeriod:13,maxWindKts:16,idealSwell:["NW","NNW","N","WNW"]},
  {id:"pupukea",          name:"Pupukea",                    region:"Oahu North Shore", location:"Pupukea, HI",         buoyId:"51201",lat:21.660,lon:-158.059,offshoreWindFrom:135,tideStation:"1612480",tideMin:0.0,tideMax:1.5,tideMovement:"any",   minHeight:5,minPeriod:13,maxWindKts:16,idealSwell:["N","NNW","NW","NNE"]},
  {id:"kammieland",       name:"Kammieland",                 region:"Oahu North Shore", location:"Haleiwa, HI",         buoyId:"51201",lat:21.633,lon:-158.076,offshoreWindFrom:135,tideStation:"1612480",tideMin:0.0,tideMax:1.5,tideMovement:"any",   minHeight:5,minPeriod:13,maxWindKts:16,idealSwell:["NW","NNW","N","WNW"]},

  // ── OAHU WEST ADDITIONS ──────────────────────────────
  {id:"maili_point",      name:"Maili Point",                region:"Oahu West",        location:"Waianae, HI",         buoyId:"51201",lat:21.397,lon:-158.173,offshoreWindFrom:90, tideStation:"1612340",tideMin:0.0,tideMax:1.8,tideMovement:"any",   minHeight:4,minPeriod:12,maxWindKts:16,idealSwell:["NW","W","WNW"]},
  {id:"nanakuli",         name:"Nanakuli Beach",             region:"Oahu West",        location:"Nanakuli, HI",        buoyId:"51201",lat:21.389,lon:-158.161,offshoreWindFrom:90, tideStation:"1612340",tideMin:0.0,tideMax:1.8,tideMovement:"any",   minHeight:4,minPeriod:11,maxWindKts:16,idealSwell:["NW","W","WNW"]},
  {id:"tracks",           name:"Tracks Beach",               region:"Oahu West",        location:"Waianae, HI",         buoyId:"51201",lat:21.450,lon:-158.185,offshoreWindFrom:90, tideStation:"1612340",tideMin:0.0,tideMax:1.8,tideMovement:"any",   minHeight:4,minPeriod:12,maxWindKts:16,idealSwell:["NW","W","WNW"]},

  // ── OAHU EAST ADDITIONS ──────────────────────────────
  {id:"sherwoods",        name:"Sherwood Forest",            region:"Oahu East",        location:"Waimanalo, HI",       buoyId:"openmeteo",dataSource:"openmeteo",lat:21.342,lon:-157.681,offshoreWindFrom:270,tideStation:"1612340",tideMin:0.0,tideMax:1.5,tideMovement:"any",   minHeight:4,minPeriod:11,maxWindKts:16,idealSwell:["E","ENE","NE"]},
  {id:"kaisers_point",    name:"Kaiser's Point",             region:"Oahu East",        location:"Hawaii Kai, HI",      buoyId:"openmeteo",dataSource:"openmeteo",lat:21.280,lon:-157.718,offshoreWindFrom:315,tideStation:"1612340",tideMin:0.0,tideMax:1.5,tideMovement:"any",   minHeight:4,minPeriod:12,maxWindKts:16,idealSwell:["S","SE","SSE"]},

  // ── MAUI ADDITIONS ───────────────────────────────────
  {id:"ukumehame",        name:"Ukumehame (Guardrails)",     region:"Maui",             location:"Olowalu, HI",         buoyId:"openmeteo",dataSource:"openmeteo",lat:20.801,lon:-156.578,offshoreWindFrom:90, tideStation:"1615680",tideMin:0.0,tideMax:2.0,tideMovement:"any",   minHeight:3,minPeriod:11,maxWindKts:16,idealSwell:["SW","S","W"]},
  {id:"laniakea_maui",    name:"Laniakea (Maui)",            region:"Maui",             location:"Kihei, HI",           buoyId:"openmeteo",dataSource:"openmeteo",lat:20.748,lon:-156.444,offshoreWindFrom:315,tideStation:"1615680",tideMin:0.0,tideMax:2.0,tideMovement:"rising",minHeight:3,minPeriod:11,maxWindKts:16,idealSwell:["S","SW","SSW"]},
  {id:"kanaha",           name:"Kanaha Beach",               region:"Maui",             location:"Kahului, HI",         buoyId:"openmeteo",dataSource:"openmeteo",lat:20.901,lon:-156.453,offshoreWindFrom:225,tideStation:"1615680",tideMin:0.0,tideMax:2.0,tideMovement:"any",   minHeight:4,minPeriod:11,maxWindKts:16,idealSwell:["N","NE","NNE"]},
  {id:"sprecks",          name:"Spreckelsville",             region:"Maui",             location:"Spreckelsville, HI",  buoyId:"openmeteo",dataSource:"openmeteo",lat:20.912,lon:-156.396,offshoreWindFrom:225,tideStation:"1615680",tideMin:0.0,tideMax:2.0,tideMovement:"any",   minHeight:4,minPeriod:12,maxWindKts:16,idealSwell:["N","NE","NNE"]},
  {id:"lower_paia",       name:"Lower Paia Bay",             region:"Maui",             location:"Paia, HI",            buoyId:"openmeteo",dataSource:"openmeteo",lat:20.928,lon:-156.355,offshoreWindFrom:225,tideStation:"1615680",tideMin:0.0,tideMax:2.0,tideMovement:"any",   minHeight:4,minPeriod:11,maxWindKts:16,idealSwell:["N","NE","NNE"]},
  {id:"kuau_cove",        name:"Kuau Cove",                  region:"Maui",             location:"Paia, HI",            buoyId:"openmeteo",dataSource:"openmeteo",lat:20.930,lon:-156.346,offshoreWindFrom:225,tideStation:"1615680",tideMin:0.0,tideMax:2.0,tideMovement:"any",   minHeight:4,minPeriod:12,maxWindKts:16,idealSwell:["N","NE","NNE"]},

  // ── KAUAI ADDITIONS ──────────────────────────────────
  {id:"brenneckes",       name:"Brennecke's Beach",          region:"Kauai",            location:"Poipu, HI",           buoyId:"openmeteo",dataSource:"openmeteo",lat:21.871,lon:-159.436,offshoreWindFrom:0,  tideStation:"1611400",tideMin:0.0,tideMax:2.0,tideMovement:"any",   minHeight:3,minPeriod:11,maxWindKts:16,idealSwell:["S","SW","SSW"]},
  {id:"family_surf",      name:"Family Surf / PK's",         region:"Kauai",            location:"Kekaha, HI",          buoyId:"openmeteo",dataSource:"openmeteo",lat:21.978,lon:-159.717,offshoreWindFrom:90, tideStation:"1611400",tideMin:0.0,tideMax:2.0,tideMovement:"any",   minHeight:4,minPeriod:12,maxWindKts:16,idealSwell:["NW","W","SW"]},
  {id:"hanalei_bowl",     name:"Hanalei Bowl",               region:"Kauai",            location:"Hanalei, HI",         buoyId:"openmeteo",dataSource:"openmeteo",lat:22.207,lon:-159.502,offshoreWindFrom:180,tideStation:"1611400",tideMin:0.0,tideMax:2.0,tideMovement:"any",   minHeight:5,minPeriod:13,maxWindKts:16,idealSwell:["N","NW","NNW"]},
  {id:"wailua_bay",       name:"Wailua Bay",                 region:"Kauai",            location:"Wailua, HI",          buoyId:"openmeteo",dataSource:"openmeteo",lat:22.056,lon:-159.326,offshoreWindFrom:270,tideStation:"1611400",tideMin:0.0,tideMax:2.0,tideMovement:"rising",minHeight:3,minPeriod:10,maxWindKts:16,idealSwell:["E","NE","ENE"]},

  // ── BIG ISLAND ADDITIONS ─────────────────────────────
  {id:"hapuna",           name:"Hapuna Beach",               region:"Big Island",       location:"Puako, HI",           buoyId:"openmeteo",dataSource:"openmeteo",lat:19.994,lon:-155.827,offshoreWindFrom:90, tideStation:"1617760",tideMin:0.0,tideMax:2.0,tideMovement:"rising",minHeight:3,minPeriod:11,maxWindKts:16,idealSwell:["NW","W","SW"]},
  {id:"kona_pier",        name:"Kona Pier (Old Airport)",    region:"Big Island",       location:"Kailua-Kona, HI",     buoyId:"openmeteo",dataSource:"openmeteo",lat:19.647,lon:-156.004,offshoreWindFrom:90, tideStation:"1617760",tideMin:0.0,tideMax:2.0,tideMovement:"any",   minHeight:3,minPeriod:11,maxWindKts:16,idealSwell:["NW","W","SW"]},
  {id:"bay_front",        name:"Bay Front / Coconut Grove",  region:"Big Island",       location:"Hilo, HI",            buoyId:"openmeteo",dataSource:"openmeteo",lat:19.730,lon:-155.063,offshoreWindFrom:270,tideStation:"1617433",tideMin:0.0,tideMax:2.0,tideMovement:"rising",minHeight:3,minPeriod:10,maxWindKts:16,idealSwell:["E","NE","ENE"]}
];
